#!/usr/bin/env python

import sys

import roslib
pkg = 'hrpsys_gazebo_tutorials'

import imp
try:
    imp.find_module(pkg)
except:
    roslib.load_manifest(pkg)

from rqt_gui.main import Main

import hrpsys_gazebo_tutorials
import hrpsys_gazebo_tutorials.jsk_hrp2_gazebo_dashboard

main = Main()
sys.exit(main.main(sys.argv, standalone=pkg))
