replace_xmls:
  - match_rule:
      tag: include
      attribute:
        - name: file
          value: '$(find jsk_pcl_ros)/launch/openni2_remote.launch'
    replaced_xml: '<include file="$(find openni2_launch)/launch/openni2.launch">  <arg name="publish_tf" value="false" /> <arg name="camera" value="camera_remote" /> <arg name="depth_registration" value="false" /> <arg name="load_driver" value="false" /> <arg name="rgb_processing" value="true" /> <arg name="depth_processing" value="true" /> <arg name="depth_registered_processing" value="true" /> <arg name="rgb_camera_info_url" value="" /> <arg name="depth_camera_info_url" value="" />  </include>'
