hrpsys_gazebo_configuration:
## velocity feedback for joint control, use parameter gains/joint_name/p_v
  use_velocity_feedback: true
## synchronized hrpsys and gazebo
# use_synchronized_command: false
# name of robot (using for namespace)
  robotname: HRP2JSK
# joint_id (order) conversion from gazebo to hrpsys, joint_id_list[gazebo_id] := hrpsys_id
  joint_id_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
# joints list used in gazebo, sizeof(joint_id_list) == sizeof(joints)
  joints:
    - RLEG_JOINT0
    - RLEG_JOINT1
    - RLEG_JOINT2
    - RLEG_JOINT3
    - RLEG_JOINT4
    - RLEG_JOINT5
    - LLEG_JOINT0
    - LLEG_JOINT1
    - LLEG_JOINT2
    - LLEG_JOINT3
    - LLEG_JOINT4
    - LLEG_JOINT5
    - CHEST_JOINT0
    - CHEST_JOINT1
    - HEAD_JOINT0
    - HEAD_JOINT1
    - RARM_JOINT0
    - RARM_JOINT1
    - RARM_JOINT2
    - RARM_JOINT3
    - RARM_JOINT4
    - RARM_JOINT5
    - RARM_JOINT6
    - RARM_JOINT7
    - LARM_JOINT0
    - LARM_JOINT1
    - LARM_JOINT2
    - LARM_JOINT3
    - LARM_JOINT4
    - LARM_JOINT5
    - LARM_JOINT6
    - LARM_JOINT7
  gains:
    CHEST_JOINT0: {p: 3000.0, d:   8.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    CHEST_JOINT1: {p: 1000.0, d:   4.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    HEAD_JOINT0:  {p:  150.0, d:   0.5, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    HEAD_JOINT1:  {p:  700.0, d:   1.5, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    LARM_JOINT0:  {p: 2000.0, d:   4.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    LARM_JOINT1:  {p: 1000.0, d:   2.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    LARM_JOINT2:  {p:  200.0, d:   0.4, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    LARM_JOINT3:  {p: 1500.0, d:   3.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    LARM_JOINT4:  {p:  200.0, d:   0.4, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    LARM_JOINT5:  {p:  400.0, d:   0.8, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    LARM_JOINT6:  {p:  400.0, d:   0.8, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    LARM_JOINT7:  {p:   20.0, d:  0.02, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    RARM_JOINT0:  {p: 2000.0, d:   4.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    RARM_JOINT1:  {p: 1000.0, d:   2.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    RARM_JOINT2:  {p:  200.0, d:   0.4, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    RARM_JOINT3:  {p: 1500.0, d:   3.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    RARM_JOINT4:  {p:  200.0, d:   0.4, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    RARM_JOINT5:  {p:  400.0, d:   0.8, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    RARM_JOINT6:  {p:  400.0, d:   0.8, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    RARM_JOINT7:  {p:   20.0, d:  0.02, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    LLEG_JOINT0:  {p: 1500.0, d:   2.0, i: 0.0, i_clamp: 0.0, p_v: 350.0} # CRTOCH-Y
    LLEG_JOINT1:  {p: 2000.0, d:   4.0, i: 0.0, i_clamp: 0.0, vp: 4.0, p_v: 350.0} # CRTOCH-R
    LLEG_JOINT2:  {p: 3800.0, d:  15.0, i: 0.0, i_clamp: 0.0, vp: 4.0, p_v: 350.0} # CRTOCH-P
    LLEG_JOINT3:  {p: 3400.0, d:  12.5, i: 0.0, i_clamp: 0.0, vp: 2.0, p_v: 350.0} # KNEE-P
    LLEG_JOINT4:  {p: 2800.0, d:  10.0, i: 0.0, i_clamp: 0.0, vp: 2.0, p_v: 350.0} # ANKLE-P
    LLEG_JOINT5:  {p: 2000.0, d:   4.0, i: 0.0, i_clamp: 0.0, vp: 2.0, p_v: 350.0} # ANKLE-R
    RLEG_JOINT0:  {p: 1500.0, d:   2.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    RLEG_JOINT1:  {p: 2000.0, d:   4.0, i: 0.0, i_clamp: 0.0, vp: 4.0, p_v: 350.0}
    RLEG_JOINT2:  {p: 3800.0, d:  15.0, i: 0.0, i_clamp: 0.0, vp: 4.0, p_v: 350.0}
    RLEG_JOINT3:  {p: 3400.0, d:  12.5, i: 0.0, i_clamp: 0.0, vp: 2.0, p_v: 350.0}
    RLEG_JOINT4:  {p: 2800.0, d:  10.0, i: 0.0, i_clamp: 0.0, vp: 2.0, p_v: 350.0}
    RLEG_JOINT5:  {p: 2000.0, d:   2.0, i: 0.0, i_clamp: 0.0, vp: 2.0, p_v: 350.0}

  force_torque_sensors:
    - rfsensor
    - lfsensor
    - rhsensor
    - lhsensor
  force_torque_sensors_config:
## TODO: add translation and rotation
    lfsensor: {joint_name: 'LLEG_JOINT5', frame_id: 'LLEG_LINK5', translation: [0, 0, -0.105], rotation: [1, 0, 0, 0]}
    rfsensor: {joint_name: 'RLEG_JOINT5', frame_id: 'RLEG_LINK5', translation: [0, 0, -0.105], rotation: [1, 0, 0, 0]}
    lhsensor: {joint_name: 'LARM_JOINT6', frame_id: 'LARM_LINK6', translation: [0, 0, -0.0775], rotation: [1, 0, 0, 0]}
    rhsensor: {joint_name: 'RARM_JOINT6', frame_id: 'RARM_LINK6', translation: [0, 0, -0.0775], rotation: [1, 0, 0, 0]}
  imu_sensors:
    - imu_sensor0
  imu_sensors_config:
## TODO: add translation and rotation
    imu_sensor0: {ros_name: 'waist_imu', link_name: 'CHEST_LINK1', frame_id: 'CHEST_LINK1'}
