hrpsys_gazebo_configuration:
## velocity feedback for joint control, use parameter gains/joint_name/p_v
  use_velocity_feedback: true
## synchronized hrpsys and gazebo
# use_synchronized_command: false
# name of robot (using for namespace)
  robotname: HRP4R
# joint_id (order) conversion from gazebo to hrpsys, joint_id_list[gazebo_id] := hrpsys_id
  joint_id_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]
# joints list used in gazebo, sizeof(joint_id_list) == sizeof(joints)
  joints:
    - R_HIP_Y
    - R_HIP_R
    - R_HIP_P
    - R_KNEE_P
    - R_ANKLE_P
    - R_ANKLE_R
    - L_HIP_Y
    - L_HIP_R
    - L_HIP_P
    - L_KNEE_P
    - L_ANKLE_P
    - L_ANKLE_R
    - CHEST_P
    - CHEST_Y
    - NECK_Y
    - NECK_P
    - R_SHOULDER_P
    - R_SHOULDER_R
    - R_SHOULDER_Y
    - R_ELBOW_P
    - R_WRIST_Y
    - R_WRIST_P
    - R_WRIST_R
    - R_HAND_J0
    - R_HAND_J1
    - L_SHOULDER_P
    - L_SHOULDER_R
    - L_SHOULDER_Y
    - L_ELBOW_P
    - L_WRIST_Y
    - L_WRIST_P
    - L_WRIST_R
    - L_HAND_J0
    - L_HAND_J1
  gains:
    R_HIP_Y:  {p: 1500.0, d:   2.0, i: 0.0, i_clamp: 0.0, p_v: 350.0} # CRTOCH-Y
    R_HIP_R:  {p: 2000.0, d:   4.0, i: 0.0, i_clamp: 0.0, vp: 4.0, p_v: 350.0} # CRTOCH-R
    R_HIP_P:  {p: 3800.0, d:  15.0, i: 0.0, i_clamp: 0.0, vp: 4.0, p_v: 350.0} # CRTOCH-P
    R_KNEE_P:  {p: 3400.0, d:  12.5, i: 0.0, i_clamp: 0.0, vp: 2.0, p_v: 350.0} # KNEE-P
    R_ANKLE_P:  {p: 2800.0, d:  10.0, i: 0.0, i_clamp: 0.0, vp: 2.0, p_v: 350.0} # ANKLE-P
    R_ANKLE_R:  {p: 2000.0, d:   4.0, i: 0.0, i_clamp: 0.0, vp: 2.0, p_v: 350.0} # ANKLE-R
    L_HIP_Y:  {p: 1500.0, d:   2.0, i: 0.0, i_clamp: 0.0, p_v: 350.0} # CRTOCH-Y
    L_HIP_R:  {p: 2000.0, d:   4.0, i: 0.0, i_clamp: 0.0, vp: 4.0, p_v: 350.0} # CRTOCH-R
    L_HIP_P:  {p: 3800.0, d:  15.0, i: 0.0, i_clamp: 0.0, vp: 4.0, p_v: 350.0} # CRTOCH-P
    L_KNEE_P:  {p: 3400.0, d:  12.5, i: 0.0, i_clamp: 0.0, vp: 2.0, p_v: 350.0} # KNEE-P
    L_ANKLE_P:  {p: 2800.0, d:  10.0, i: 0.0, i_clamp: 0.0, vp: 2.0, p_v: 350.0} # ANKLE-P
    L_ANKLE_R:  {p: 2000.0, d:   4.0, i: 0.0, i_clamp: 0.0, vp: 2.0, p_v: 350.0} # ANKLE-R
    CHEST_P: {p: 3000.0, d:   8.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    CHEST_Y: {p: 1000.0, d:   4.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    NECK_Y:  {p:  150.0, d:   0.5, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    NECK_P:  {p:  700.0, d:   1.5, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    R_SHOULDER_P:  {p: 2000.0, d:   4.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    R_SHOULDER_R:  {p: 1000.0, d:   2.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    R_SHOULDER_Y:  {p:  200.0, d:   0.4, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    R_ELBOW_P:  {p: 1500.0, d:   3.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    R_WRIST_Y:  {p:  200.0, d:   0.4, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    R_WRIST_P:  {p:  400.0, d:   0.8, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    R_WRIST_R:  {p:  400.0, d:   0.8, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    R_HAND_J0:  {p:   20.0, d:  0.02, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    R_HAND_J1:  {p: 2000.0, d:   4.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    L_SHOULDER_P:  {p: 2000.0, d:   4.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    L_SHOULDER_R:  {p: 1000.0, d:   2.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    L_SHOULDER_Y:  {p:  200.0, d:   0.4, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    L_ELBOW_P:  {p: 1500.0, d:   3.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    L_WRIST_Y:  {p:  200.0, d:   0.4, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    L_WRIST_P:  {p:  400.0, d:   0.8, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    L_WRIST_R:  {p:  400.0, d:   0.8, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    L_HAND_J0:  {p:   20.0, d:  0.02, i: 0.0, i_clamp: 0.0, p_v: 350.0}
    L_HAND_J1:  {p: 2000.0, d:   4.0, i: 0.0, i_clamp: 0.0, p_v: 350.0}
  force_torque_sensors:
    - rfsensor
    - lfsensor
  force_torque_sensors_config:
## TODO: add translation and rotation
    lfsensor: {joint_name: 'L_ANKLE_R', frame_id: 'L_ANKLE_R_LINK', translation: [0, 0, -0.093], rotation: [1, 0, 0, 0]}
    rfsensor: {joint_name: 'R_ANKLE_R', frame_id: 'R_ANKLE_R_LINK', translation: [0, 0, -0.093], rotation: [1, 0, 0, 0]}
  imu_sensors:
    - imu_sensor0
  imu_sensors_config:
## TODO: add translation and rotation
    imu_sensor0: {ros_name: 'waist_imu', link_name: 'BODY', frame_id: 'BODY'}
